### ISSUE TITLE
在 13.0 Beta 上闪退

### ISSUE THREAD

**Issue by JounQin** [isaced/V2exOS#1]
版本13.0 Beta版(22A5321d)

尝试本地构建了一个版本，进入 post 详情就闪退

（另外还没设置应用图标有点儿丑，哈哈哈

**Comment by isaced** [comment]
[accessToken](https://v2ex.com/help/personal-access-token) 有填写吗？（_还在开发 UI 让填入 token_）

https://github.com/isaced/V2exOS/blob/06b6fd4b622dc48c253f632aea0fc4aa3af302bc/V2exOS/V2exOSApp.swift#L11

macOS Ventura 还没升级，过两天试试。

 ICON 还在构思中，简单画了两笔 😄

<img width="100" src="https://user-images.githubusercontent.com/2088605/183918458-97659451-4467-46f2-953a-2cb3a9b51eea.png" />
