### ISSUE TITLE
图标是否可以适配Monterey及以上呀？

### ISSUE THREAD

**Issue by Sunjinwei** [isaced/V2exOS#17]
https://www.dropbox.com/s/rld2wejki2muz9j/v2ex.icns?dl=0

图标造型取自v2ex网站fav icon.

**Comment by isaced** [comment]
不太明白图标适配 Monterey 是什么意思？

**Comment by Sunjinwei** [comment]
就是用圆角矩形的图标，如链接所示。

**Comment by isaced** [comment]
比较好奇为什么适配 Monterey 需要圆角矩形图标呢？ [App icons 设计规范](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/) 中也没有要求一定要完全圆角吧？

**Comment by Sunjinwei** [comment]
[Dock图标](https://i.imgur.com/JRYisee.png)话说这样是不是有点不太和谐

**Comment by Sunjinwei** [comment]
在 macOS 中，应用程序图标共享一组通用的视觉属性，包括圆角矩形、正面透视、水平位置和统一的阴影。这些属性植根于 macOS 设计语言，在呈现和谐用户体验的同时，展示了人们期望在 macOS 中栩栩如生的渲染风格——App icons设计规范。
通用的视觉属性：圆角矩形。

**Comment by isaced** [comment]
可是很多 macOS App 都不是圆角矩形的图标，个人感觉并没有特别违和？

|              |                      | |
|----------------------|--------------------------|---------|
| <img width="158" alt="image" src="https://user-images.githubusercontent.com/2088605/195617433-f11f2cc3-ef2e-44d6-b362-3990008a5109.png">       | <img width="142" alt="image" src="https://user-images.githubusercontent.com/2088605/195617565-68548fea-65ed-46a8-b299-84ea70e7d7a1.png">            | <img width="137" alt="image" src="https://user-images.githubusercontent.com/2088605/195617709-b36efac8-4d56-4a8e-aa11-487a97333259.png"> |
<img width="417" alt="image" src="https://user-images.githubusercontent.com/2088605/195617833-0b2249b4-4e61-439b-b916-45fcebfbfad5.png">

**Comment by isaced** [comment]
不太想和官方用同样的 icon，毕竟是一个第三方客户端，如果基于现有的图形改成圆角的话是这个感觉：

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2088605/195619591-4bd48811-5cef-4e46-aaa5-6e85880b0766.png">

**Comment by isaced** [comment]
v1.5 版本已更新
