### ISSUE TITLE
建议增加大字体模式

### ISSUE THREAD

**Issue by hkongm** [isaced/V2exOS#18]
中年人，字大点省眼睛

感谢作者！

**Comment by isaced** [comment]
理解，考虑在设置面板中增加 [字号] 调整选项

**Comment by absir1949** [comment]
同需

**Comment by isaced** [comment]
[v1.6](https://github.com/isaced/V2exOS/releases/tag/1.6) 增加了字体大小设置功能（目前仅生效于正文和评论），可以试一试，有问题请随时反馈，谢谢 🙏

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/2088605/206748938-364f0dbd-9659-4aec-8dae-aac6b4d4bc6e.png">
