### ISSUE TITLE
添加搜索功能

### ISSUE THREAD

**Issue by jkwroi24io9342fsdjklAdf** [isaced/V2exOS#24]
好像没找到搜索功能哦

**Comment by isaced** [comment]
Commit https://github.com/isaced/V2exOS/commit/1eefa6f5e1090900fedb9aa777efac06143574db

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2088605/206619693-8ce78386-5bfa-4a03-bb46-176e688bef7b.png">

**Comment by newte88** [comment]
是否可以使用[sov2ex](https://github.com/Bynil/sov2ex)库实现搜索功能？

**Comment by isaced** [comment]
@newte88 看了下 sov2ex 有提供 [API](https://github.com/bynil/sov2ex/blob/v2/API.md)，而且速度还不错，可以尝试集成。 👍
