### ISSUE TITLE
滑动帖子栏时动画卡顿

### ISSUE THREAD

**Issue by kid1412621** [isaced/V2exOS#25]

**Comment by isaced** [comment]
是指右边的评论列表滑动卡吗？

**Comment by isaced** [comment]
发布了 [macOS v1.7 Beta.1](https://github.com/isaced/V2exOS/releases/tag/macos_1.7.beta.1) 优化了 macOS 端评论列表加载性能，可以试试看。

**Comment by kid1412621** [comment]
> 发布了 [macOS v1.7 Beta.1](https://github.com/isaced/V2exOS/releases/tag/macos_1.7.beta.1) 优化了 macOS 端评论列表加载性能，可以试试看。

感谢，已改善，请问收藏节点大概什么时候出呀

**Comment by isaced** [comment]
> > 发布了 [macOS v1.7 Beta.1](https://github.com/isaced/V2exOS/releases/tag/macos_1.7.beta.1) 优化了 macOS 端评论列表加载性能，可以试试看。
> 
> 感谢，已改善，请问收藏节点大概什么时候出呀

是指可以选择节点进行收藏，左边可以快速定位收藏的节点查看其帖子吗？

V2EX API 开放很有限，貌似没找到收藏节点相关的 [API](https://v2ex.com/help/api)，真要做只能本地存下来。

**Comment by kid1412621** [comment]
就是指列出收藏的节点，我不太确定这个 app 是怎么做的。
https://github.com/fan123199/v2ex-simple
实在不行允许自定义侧边栏显示节点

**Comment by isaced** [comment]
> 就是指列出收藏的节点，我不太确定这个 app 是怎么做的。 https://github.com/fan123199/v2ex-simple 实在不行允许自定义侧边栏显示节点

好的，我看一下
