### ISSUE TITLE
tvOS版本发不到AppStore了吗？

### ISSUE THREAD

**Issue by androidcn** [isaced/V2exOS#26]

**Comment by isaced** [comment]
有发的，和之前是同一个应用

https://apps.apple.com/cn/app/v2exos/id6443544914?platform=appleTV

<img width="692" alt="image" src="https://user-images.githubusercontent.com/2088605/225942997-494dc78e-8082-45b5-9d42-2a073a2b06ab.png">

**Comment by androidcn** [comment]
优秀，我先去体验

**Comment by androidcn** [comment]
![image](https://user-images.githubusercontent.com/271715/226079007-ee6ffe93-71dc-49b5-b535-36b253d72676.jpeg)

打开后，空白，网络没问题

**Comment by isaced** [comment]
下个版本我加个错误提示看看
