### ISSUE TITLE
请问可不可以将ios安装包ipa直接发在release里面呢

### ISSUE THREAD

**Issue by AlanDinkle** [isaced/V2exOS#30]
testflight没有名额了，可以自签名解决

**Comment by isaced** [comment]
好的，打包发布了 iOS 的 `.ipa` Release，可以下载安装。

https://github.com/isaced/V2exOS/releases/tag/iOS_1.0

**Comment by AlanDinkle** [comment]
谢谢🙏，但是用巨魔安装后报错，ios15.7，可能是因为这个包是testflight签名过的，因为主页面中app名字前出现了黄色的点

**Comment by isaced** [comment]
TestFlight 之前过期了，目前已经重新发布 TestFlight 版本，也可以在 TestFlight 安装了。

https://testflight.apple.com/join/MOtKdxHH
