### ISSUE TITLE
建议增加颜色区分

### ISSUE THREAD

**Issue by ch634421335** [isaced/V2exOS#6]
例如消息页和帖子中的回复，可以增加 @用户名 为深色，链接或者主题为蓝色。现在都是黑白看起来有点疲劳，不便于分辨有效信息。

**Comment by isaced** [comment]
|V2ex(web)	| V2exOS |
|---	|---	|
|<img width="261" alt="image" src="https://user-images.githubusercontent.com/2088605/192745025-06e763ae-8503-425a-a794-57e765d34ac7.png">	|<img width="188" alt="image" src="https://user-images.githubusercontent.com/2088605/192745112-46f08ba4-4e54-4029-9147-eb9c04672945.png">	|

@ch634421335  感谢提出建议，对比了一下网站的时间文本颜色更淡，另外或许是有头像的展示增大了间距和辨识度，我把颜色再调整一下，头像加上吧。

**Comment by MoonlightSmile** [comment]
我有个思路
把 @人名 替换为 **人名**
把 url 替换 为 [url](url) 

我研究下swift 怎么使用 string.replace 提个pr

**Comment by isaced** [comment]
> <img src="https://user-images.githubusercontent.com/2088605/193239189-7badb9f8-dd40-4b63-a526-c06af485441e.png" height="200">

v1.2 版本的评论列表加了头像，感觉要好一些。

@MoonlightSmile 嗯，这两个点很不错，甚至 `@人名` 可以点击链接跳转到个人主页，期待你的 PR。 👍
